version: '2.1'
services:
  ad_mongodb:
    image: mongo
    container_name: ad_mongo
    restart: always
    ports:
      - ${AD_MONGO_PORT}:27017
    volumes:
      - ./data/mongo/configdb:/data/configdb
      - ./data/mongo/db:/data/db
      - ./data/mongodb/log:/var/log/mongodb  # 挂载日志目录
    # command: mongod --auth # 如果要设置密码请开启
    #初始化管理员用户名和密码
    environment:
     MONGO_INITDB_ROOT_USERNAME: ${AD_MONGO_USER}
     MONGO_INITDB_ROOT_PASSWORD: ${AD_MONGO_PWD}
     MONGO_INITDB_DATABASE: ${AD_MONGO_DATABASE}
    tty: true

  ad_elasticsearch:
    image: elasticsearch:7.9.3
    container_name: ad_elasticsearch
    restart: always
    environment:
      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m" #设置使用jvm内存大小
    volumes:
      - ./data/elasticsearch/data:/usr/share/elasticsearch/data:rw,z
      - ./data/elasticsearch/logs:/user/share/elasticsearch/logs:rw,z
      - ./esplugins:/usr/share/elasticsearch/plugins:z
    ports:
      - ${AD_ES_PORT}:9200

  kibana:
    image: kibana:7.9.3
    container_name: ad_kibana
    restart: always
    links:
      - ad_elasticsearch:elasticsearch #可以用es这个域名访问elasticsearch服务
    depends_on:
      - ad_elasticsearch #kibana在elasticsearch启动之后再启动
    environment:
      - "elasticsearch.hosts=http://elasticsearch:9200" #设置访问elasticsearch的地址
    ports:
      - 5601:5601
      
  ad_redis:
    image: redis:latest
    container_name: ad_redis
    restart: always
    # 使用配置文件进行启动，可以选择性设置密码requirepass
    command: redis-server /etc/redis/redis.conf
    ports:
      - ${AD_REDIS_PORT}:6379
    volumes:
      - ./data/redis:/data
      - ./data/redis/redis.conf:/etc/redis/redis.conf
